name: hoom_sound
description: "Projet Flutter intégrant l’API Mistral AI et l’API Spotify avec authentification via Supabase."
publish_to: "none" # Ce projet n'est pas destiné à être publié sur pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.8.4      # Pour l'authentification et la gestion des données via Supabase
  http: ^1.3.0              # Pour réaliser des appels HTTP (Mistral AI, Spotify, etc.)
  flutter_web_auth_2: ^4.1.0        # Pour gérer l'authentification OAuth (Spotify)
  just_audio: ^0.9.32
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
